### ISSUE TITLE
Adding new TTS voices?

### ISSUE THREAD

**Issue by Vanillio7** [IAHispano/Applio-Plugins#2]
Is it possible to add TTS voices that were made from eleven labs into this plug in? If so, how?

**Comment by Maville-07** [comment]
it could, the api technically allows it via a url of the voice but the code would have to be adapted to be able to place the voice

https://elevenlabs.io/docs/api-reference/text-to-speech
However it would not serve much purpose to place trained voices inside the platform since the elevenlabs plugin is designed to use the voices as input audio for the model created in RVC (?)

**Comment by Vanillio7** [comment]
@aitronssesin Yes that's true, thank you.
